package com.epam.finaltask.model.enums;

public enum StatusCodes {
    OK,
    ENTITY_NOT_FOUND,
    INVALID_DATA,
    INVALID_CREDENTIALS,
    VALUE_NOT_FOUND,
    DUPLICATE_USERNAME,
    DUPLICATE_ORDER,
    FORBIDDEN,
    INVALID_VOUCHER_OPERATION,
    INTERNAL_SERVER_ERROR,
    TOKEN_ALREADY_USED,
    TOKEN_EXPIRED
}
